### ISSUE TITLE
May be wrong method?

### ISSUE THREAD

**Issue by ea3hsp** [Aterocana/mosquitto-go-auth-example#1]
https://github.com/Aterocana/mosquitto-go-auth-example/blob/b3167c4be9d9739c10d49bfb816e636af51e6d06/server/srv.go#L108

should be: authorized = srv.canSub(res.Username, res.Topic) ?

**Comment by Aterocana** [comment]
That's right, thanks a lot.
Fixed [here](https://github.com/Aterocana/mosquitto-go-auth-example/commit/433ba53b8ee2f527a4ed45bb8e312b2e11ff3202).
